#pragma once
#include "sim/graphics/brain_fonts/font_common.h"

// generated by SimVex fontconverter

namespace sim{ namespace font{
extern font_info noto_sans_mono_30_info;

extern std::map<char, glyph_info> noto_sans_mono_30_glyph_info;

extern const int noto_sans_mono_30_tex_size;
extern const int noto_sans_mono_30_tex_width;
extern const int noto_sans_mono_30_tex_height;
extern const uint8_t noto_sans_mono_30_tex[101376];
}}
