#pragma once
#include "font_common.h"

// generated by SimVex fontconverter

namespace sim::font{
extern font_info noto_sans_mono_12_info;

extern std::map<char, glyph_info> noto_sans_mono_12_glyph_info;

extern const int noto_sans_mono_12_tex_size;
extern const uint8_t noto_sans_mono_12_tex[16224];
}
