#pragma once
#include "font_common.h"

// generated by SimVex fontconverter

namespace sim::font{
extern font_info noto_sans_mono_60_info;

extern std::map<char, glyph_info> noto_sans_mono_60_glyph_info;

extern const int noto_sans_mono_60_tex_size;
extern const int noto_sans_mono_60_tex_width;
extern const int noto_sans_mono_60_tex_height;
extern const uint8_t noto_sans_mono_60_tex[386880];
}
